import "./globals.css";

import { Press_Start_2P, Roboto_Mono } from "next/font/google";

import type { Metadata } from "next";

const pressStart2P = Press_Start_2P({
  variable: "--font-heading",
  subsets: ["latin"],
  weight: "400",
});

const robotoMono = Roboto_Mono({
  subsets: ["latin"],
  variable: "--font-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${pressStart2P.variable} ${robotoMono.variable} antialiased bg-background`}
      >
        {children}
      </body>
    </html>
  );
}
